# Generated by Django 5.1.5 on 2025-02-10 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserCrimeReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('typeofCrime', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=10000)),
                ('dateofCrime', models.DateField()),
                ('timeofCrime', models.TimeField()),
                ('status', models.CharField(max_length=200)),
            ],
        ),
    ]
