# Generated by Django 5.1.5 on 2025-03-17 11:44

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_usercrimereport'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserReports',
        ),
        migrations.RemoveField(
            model_name='usercrimereport',
            name='dateofCrime',
        ),
        migrations.RemoveField(
            model_name='usercrimereport',
            name='timeofCrime',
        ),
        migrations.AddField(
            model_name='usercrimereport',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Reported Date'),
        ),
        migrations.AlterField(
            model_name='usercrimereport',
            name='description',
            field=models.TextField(default='No description provided.', verbose_name='Crime Description'),
        ),
        migrations.AlterField(
            model_name='usercrimereport',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('In Progress', 'In Progress'), ('Resolved', 'Resolved'), ('Rejected', 'Rejected')], default='Pending', max_length=20, verbose_name='Report Status'),
        ),
        migrations.AlterField(
            model_name='usercrimereport',
            name='typeofCrime',
            field=models.CharField(max_length=100, verbose_name='Type of Crime'),
        ),
    ]
