# Generated by Django 5.1.5 on 2025-03-17 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_delete_userreports_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usercrimereport',
            name='location',
            field=models.CharField(default='Unknown Location', max_length=255, verbose_name='Crime Location'),
        ),
    ]
