# Generated by Django 5.1.5 on 2025-03-17 18:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_usercrimereport_location'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='usercrimereport',
            name='admin_notes',
            field=models.TextField(blank=True, null=True, verbose_name='Admin Notes'),
        ),
        migrations.AddField(
            model_name='usercrimereport',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='usercrimereport',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Under Investigation', 'Under Investigation'), ('Resolved', 'Resolved'), ('Rejected', 'Rejected')], default='Pending', max_length=20, verbose_name='Report Status'),
        ),
    ]
