# Generated by Django 5.1.5 on 2025-04-13 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_usercrimereport_admin_notes_usercrimereport_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usercrimereport',
            name='priority',
            field=models.IntegerField(choices=[(1, 'Very Low'), (2, 'Low'), (3, 'Medium'), (4, 'High'), (5, 'Critical')], default=2, verbose_name='Priority Level'),
        ),
    ]
