# Generated by Django 5.1.5 on 2025-04-13 05:25

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_usercrimereport_priority'),
    ]

    operations = [
        migrations.AddField(
            model_name='usercrimereport',
            name='submitted_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Submitted At'),
        ),
    ]
