# Generated by Django 5.1.5 on 2025-04-13 08:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_usercrimereport_submitted_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='EvidencePhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='evidence_photos/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='main.usercrimereport')),
            ],
        ),
    ]
