# Generated by Django 5.1.5 on 2025-04-21 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_alter_usercrimereport_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='usercrimereport',
            name='latitude',
            field=models.CharField(default='0', max_length=255, verbose_name='Latitude'),
        ),
        migrations.AddField(
            model_name='usercrimereport',
            name='longititude',
            field=models.CharField(default='0', max_length=255, verbose_name='Longitude'),
        ),
    ]
