# Generated by Django 5.1.5 on 2025-04-21 16:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_usercrimereport_latitude_usercrimereport_longititude'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usercrimereport',
            old_name='longititude',
            new_name='longitude',
        ),
    ]
