# Generated by Django 5.1.5 on 2025-06-27 09:46

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alerts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('typeofAlert', models.CharField(max_length=100, verbose_name='Type of Alert')),
                ('description', models.TextField(default='No description provided.', verbose_name='Crime Description')),
                ('location', models.CharField(default='Unknown Location', max_length=255, verbose_name='Crime Location')),
                ('date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Reported Date')),
                ('submitted_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Submitted At')),
                ('priority', models.IntegerField(choices=[(1, 'Information'), (2, 'Warning'), (3, 'Critical')], default=1, verbose_name='Priority Level')),
            ],
        ),
    ]
