# Generated by Django 5.1.5 on 2025-06-27 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_alerts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alerts',
            name='priority',
            field=models.IntegerField(choices=[(1, 'info'), (2, 'warning'), (3, 'critical')], default=1, verbose_name='Priority Level'),
        ),
    ]
