# Generated by Django 5.1.5 on 2025-06-27 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_alter_alerts_priority'),
    ]

    operations = [
        migrations.RenameField(
            model_name='alerts',
            old_name='typeofAlert',
            new_name='title',
        ),
        migrations.RemoveField(
            model_name='alerts',
            name='description',
        ),
        migrations.RemoveField(
            model_name='alerts',
            name='location',
        ),
        migrations.AddField(
            model_name='alerts',
            name='area',
            field=models.CharField(default='Unknown Location', max_length=255, verbose_name='area'),
        ),
        migrations.AddField(
            model_name='alerts',
            name='message',
            field=models.TextField(default='No description provided.', verbose_name='Alert Description'),
        ),
    ]
