# Generated by Django 5.1.5 on 2025-06-27 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_rename_typeofalert_alerts_title_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alerts',
            name='priority',
        ),
        migrations.AddField(
            model_name='alerts',
            name='severity',
            field=models.IntegerField(choices=[(1, 'info'), (2, 'warning'), (3, 'critical')], default=1, verbose_name='Severity Level'),
        ),
    ]
