# Generated by Django 5.1.5 on 2025-06-27 10:25

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_remove_alerts_priority_alerts_severity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alerts',
            name='date',
        ),
        migrations.RemoveField(
            model_name='alerts',
            name='submitted_at',
        ),
        migrations.AddField(
            model_name='alerts',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Created At'),
        ),
    ]
