# Generated by Django 5.1.5 on 2025-06-27 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_remove_alerts_date_remove_alerts_submitted_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alerts',
            name='severity',
            field=models.CharField(choices=[('info', 'Information'), ('warning', 'Warning'), ('critical', 'Critical')], default='info', max_length=10),
        ),
    ]
